"""change room number to auto increment int

Revision ID: 3ceabac305a3
Revises: 4f8435f098f5
Create Date: 2025-03-14 06:12:57.656649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3ceabac305a3"
down_revision: Union[str, None] = "4f8435f098f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "room",
        "room_number",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "room",
        "room_number",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
