"""add room user slot index

Revision ID: 4ae002ce3c29
Revises: 9da7ae84398d
Create Date: 2025-04-07 17:39:22.597728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4ae002ce3c29"
down_revision: Union[str, None] = "9da7ae84398d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roomuser", sa.Column("slot_index", sa.Integer(), nullable=False))
    op.drop_constraint("fk_roomuser_user_uid", "roomuser", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_roomuser_user_uid", "roomuser", "user", ["user_uid"], ["uid"]
    )
    op.drop_column("roomuser", "slot_index")
    # ### end Alembic commands ###
