"""rename roomuser

Revision ID: 6ca81a4b31e4
Revises: 6302c9ac134c
Create Date: 2025-03-13 17:12:47.379808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6ca81a4b31e4"
down_revision: Union[str, None] = "6302c9ac134c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("roomuser", "room_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("room_user", "roomuser")
    # ### end Alembic commands ###
