"""Add game_id to Room

Revision ID: 6ef04a1a3b99
Revises: fe10e2bd9e9b
Create Date: 2025-06-04 16:55:36.254892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6ef04a1a3b99"
down_revision: Union[str, None] = "fe10e2bd9e9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room", sa.Column("game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_room_game_id"), "room", ["game_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_game_id"), table_name="room")
    op.drop_column("room", "game_id")
    # ### end Alembic commands ###
