"""add updated_at

Revision ID: a89e059d6dee
Revises: f8992f42c998
Create Date: 2025-03-05 06:33:07.814311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a89e059d6dee"
down_revision: Union[str, None] = "f8992f42c998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index("ix_user_uid", table_name="user")
    op.drop_column("user", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.create_index("ix_user_uid", "user", ["uid"], unique=True)
    op.drop_column("user", "updated_at")
    # ### end Alembic commands ###
